MiniBlog/MiniBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('Mini-Blog/',include('blog.urls',namespace='Mini-Blog')),
]
if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MiniBlog/accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'
urlpatterns = [
   path('signup/',views.signup,name='signup'),
   path('profile/',views.profile,name='profile'),
   path('edit_profile/',views.edit_profile,name='edit_profile'),
]

MiniBlog/blog/urls.py
from django.urls import path
from .import views

app_name = 'blog'
urlpatterns = [
    path('home/',views.home,name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/<int:id>/',views.detail_post,name='detail_post'),
    path('contact/', views.contact, name='contact'),
    path('AddPost/',views.add_post,name='add_post'),
    path('UpdatePost/<int:id>/',views.update_post,name='update_post'),
    path('DeletePost/<int:id>/',views.delete_post,name='delete_post'),
]

MiniBlog/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Profile(models.Model):
    objects = None
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/', null=True, blank=True)
    number_phone = models.CharField(max_length=40)
    city = models.ForeignKey('City', on_delete=models.CASCADE, related_name='user_city', null=True, blank=True)

    def __str__(self):
        return '%s ' % self.user.username


def create_profile(sender, **kwargs):
    if kwargs['created']:
        Profile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)


class City(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

MiniBlog/blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=100)
    desc = models.TextField(max_length=4000)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User,related_name='user',on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Info(models.Model):
    objects = None
    place = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=100)
    email = models.EmailField(max_length=100) 
    
    def __str__(self):
        return self.email

MiniBlog/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image','number_phone','city']

MiniBlog/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','desc']
        labels = {'title':'Title','desc':'Description'}
        widgets = {'title':forms.TextInput(attrs={'class':'form-control'}),
        'desc':forms.Textarea(attrs={'class':'form-control'})
        }

MiniBlog/accounts/views.py
from django.shortcuts import render, redirect
from .forms import SignUpForm
from django.contrib.auth import authenticate, login as auth_login
from .models import Profile
from .forms import ProfileForm, UserForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def signup(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Congratulations!! You Have Become An Author')
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            auth_login(request, user)
            return redirect('Mini-Blog:home')
        else:
            form = SignUpForm()

    return render(request, 'registration/signup.html', {'form': form})

@login_required(login_url='login')
def profile(request):
    my_profile = Profile.objects.get(user=request.user)
    return render(request, 'accounts/profile.html', {'my_profile': my_profile})

@login_required(login_url='login')
def edit_profile(request):
    my_profile = Profile.objects.get(user=request.user)
    user_profile = ProfileForm(instance=my_profile)
    user_form = UserForm(instance=request.user)
    if request.method == 'POST':
        user_profile = ProfileForm(request.POST, request.FILES, instance=my_profile)
        user_form = UserForm(request.POST, instance=request.user)
        if user_profile.is_valid() and user_form.is_valid():
            user_form.save()
            profile1 = user_profile.save(commit=False)
            profile1.user = request.user
            profile1.save()
            return redirect('accounts:profile')
        else:
            my_profile = Profile.objects.get(user=request.user)
            user_profile = ProfileForm(instance=my_profile)
    return render(request, 'accounts/profile_edit.html', {'user_profile': user_profile, 'user_form': user_form})

MiniBlog/blog/views.py
from django.shortcuts import render,redirect
from .models import Post,Info
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.conf import settings 
from django.core.mail import send_mail
# Home Page
def home(request):
    posts = Post.objects.all()
    paginator = Paginator(posts,3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)   
    return render(request,'blog/home.html',{'posts':posts})

# detail post
def detail_post(request,id):
    posts = Post.objects.get(id=id)   
    return render(request,'blog/detail_post.html',{'posts':posts})     

# Contact Page
def contact(request):
    info = Info.objects.first()
    if request.method == 'POST':
        subject = request.POST['subject']
        email = request.POST['email']
        message = request.POST['message']
            
        send_mail(
                subject,
                message,
                settings.EMAIL_HOST_USER,
                [email],
         )
    return render(request,'blog/contact.html',{'info':info})

# Dashboard Page
def dashboard(request):
    if request.user.is_authenticated:
        posts = Post.objects.all()
        paginator = Paginator(posts,3)
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)   
        return render(request,'blog/dashboard.html',{'posts':posts})
    else:
        return redirect('login')  

# Add New Post
@login_required(login_url='login')          
def add_post(request):
    form = PostForm()    
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form1 = form.save(commit=False)
            form1.created_by = request.user
            form1.save()
        else:
             form = PostForm()
    return render(request,'blog/add_post.html',{'form':form})

# Update Post
@login_required(login_url='login')          
def update_post(request,id):
        post = Post.objects.get(id=id)
        form = PostForm(instance=post)
        if request.method == 'POST':
                 form = PostForm(request.POST,instance=post)
                 if form.is_valid():
                     form.save()
                 else:       
                     post = Post.objects.get(id=id)
                     form = PostForm(instance=post)
        return render(request,'blog/update_post.html',{'form':form})             

# Delete Post
@login_required(login_url='login') 
def delete_post(request,id):
    post = Post.objects.get(id=id)
    post.delete()
    return redirect('Mini-Blog:home')

MiniBlog/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% load static %}

{% block content1 %}
  <h2 style="margin-left:300px; margin-top:80px;" class="text-center"> Profile Page  </h2>
<div class="container" style="margin-top:30px;margin-left:160px; background-color:#fff; color:#000">

                <div class="col-lg-6 col-sm-4" style="margin-left: 100px;;">
                        <div class="summery_header">

                             {% if my_profile.image %}
                                     <img src="{{my_profile.image.url}}" style="margin-left:340px; margin-top:40px;" width="110" height="110" alt="profile image">
                             {% else %}
                                    <img src="{% static 'img/user.png' %}" style="margin-left:340px; margin-top:10px;" width="110" height="110" alt="profile image">
                             {% endif %}
                        </div>
                        <div class="job_content" style="margin-top:-100px;">
                            <ul>
                                <li> Name : <span>{{my_profile}}</span></li>
                                <li> E-Mail : <span>{{my_profile.user.email}}</span></li>
                                <li> City : <span>{{my_profile.city}}</span></li>
                                <li> Phone-Number : <span> {{my_profile.number_phone}} </span></li>
                            </ul>
                            <br>
                             <p><a href="{% url 'accounts:edit_profile' %}"  class='btn btn-primary' style="width:100%; margin-top:-10px;"> Edit Profile</a></p>
                            <br>
                        </div>
                    </div>
                </div>

{% endblock %}

MiniBlog/accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}


        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4 style="margin-left:400px; margin-top:40px;"> Edit Profile </h4>

                        <form method="POST" enctype="multipart/form-data"  style="margin-top:10px;">
                            {% csrf_token %}
                            {% bootstrap_form user_form %}
                            {% bootstrap_form user_profile %}
                            <button class="btn btn-success" style="width:100%;" type="submit"> Save Changes </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

MiniBlog/blog/templates/blog/add_post.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="col-sm-10">
        <h1 class="text-white my-5" style="margin:auto; "> Dashboard / Add Post </h3>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Add Post" class="btn btn-success">
            <a href="{% url 'Mini-Blog:dashboard' %}" class="btn btn-danger"> Cancel </a>
        </form>    
    </div>
{% endblock %}

MiniBlog/blog/templates/blog/contact.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
      <section class="contact-section section_padding">
        <div class="container">
          <div class="row">
            <div class="col-12">
              <h2 class="contact-title" style="margin-top: 20px;">Get in Touch</h2>
            </div>
            <div class="col-lg-8">
              <form class="form-contact contact_form" method="post" >
                {% csrf_token %}
                <div class="row" style="margin-top: 20px;">
                  <div class="col-12">
                    <div class="form-group">
                      <input class="form-control" name="subject" id="subject" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Subject'" placeholder = 'Enter Subject'>
                    </div>
                  </div>
                  <div class="col-sm-12">
                    <div class="form-group">
                      <input class="form-control" name="email" id="email" type="email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" placeholder = 'Enter email address'>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-group">
    
                        <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9"  placeholder = 'Enter Message'></textarea>
                    </div>
                  </div>
    
                </div>
                <div class="form-group mt-3">
                  <input type="submit" class="btn btn-success" style="width:100%;" value="send message">
                </div>
              </form>
            </div>
            <div class="col-lg-4">
              <div class="media contact-info">
                <span class="contact-info__icon"><i class="ti-home"></i></span>
                <div class="media-body">
                  <p> Location :</p>
                  <h4>{{info.place}}</h4>
                </div>
              </div>
              <br>
              <div class="media contact-info">
                <span class="contact-info__icon"><i class="ti-tablet"></i></span>
                <div class="media-body">
                  <p> Phone Number :</p>
                  <h4>{{info.phone_number}}</h4>
                  <p>Mon to Fri 9am to 6pm</p>
                </div>
              </div>
              <br>
              <div class="media contact-info">
                <span class="contact-info__icon"><i class="ti-email"></i></span>
                <div class="media-body">
                  <p> E-Mail :</p>
                  <h4>{{info.email}}</h4>
                  <p>Send us your query anytime!</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- ================ contact section end ================= -->
{% endblock %}

MiniBlog/blog/templates/blog/dashboard.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="col-sm-10">
        <h1 class="text-white my-5" style="margin-left:360px;"> DashBoard Page </h3>
         <a href="{% url 'Mini-Blog:add_post' %}" class="btn btn-success" style="margin-left:310px; width:40%;"> Add New Post </a>   
        <h4 class="text-center alert alert-info mt-3" style="margin-left:80px;" > Show Post Information </h4>
        
        {% if posts %}
            <table class="text-center table table-hover bg-white;" style="margin-left:40px;">
                <thead>
                    <tr>
                        <th scope="col" style="width:2%;"> ID </th>
                        <th scope="col" style="width:28%;"> Title </th>
                        <th scope="col" style="width:55%;"> Description </th>  
                        <th scope="col" style="width:15%;"> Action </th>                                              
                    </tr>
                </thead>
                <tbody>
                    {% for post in posts  %}
                    <tr>
                        <th scope="row"> {{post.id}} </th>
                        <td> {{post.title}} </td>
                        <td> {{post.desc|truncatewords:8}} </td>
                        
                        <td class="text-center">
                            {% if post.created_by == request.user %}
                            <a href="{% url 'Mini-Blog:update_post' post.id %}" class="btn btn-warning btn-sm"> Edit </a>
                            <a href="{% url 'Mini-Blog:delete_post' post.id %}" class="btn btn-danger btn-sm d-inline"> Delete </a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <h4 class="text-center alert alert-warning"> No Records </h4>    
        {% endif %}
    </div>
 
    <nav aria-label="doctor-pagination" style="margin-left:415px; margin-bottom:40px;">
        <ul class="pagination">
            <!-- Start Of Previous -->
                {% if posts.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{posts.previous_page_number}}"> Previous </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link"> Previous </a>
                    </li>
                {% endif %}
            <!-- End Of Previous -->
    
            <!-- Start Of Loop -->
                {% for page_num in posts.paginator.page_range %}
                    {% if posts_num == page_num %}
                        <li class="page-item active">
                             {{page_num}
                            <span class="sr-only">(current)</span>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_num}}"> {{page_num}} </a>
                        </li>
                    {% endif %}
                {% endfor %}
             <!-- Start Of Loop -->
    
    
             <!-- Start Of Next -->
                {% if posts.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{posts.next_page_number}}"> Next </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link"> Next </a>
                    </li>
                {% endif %}
            <!-- End Of Next -->       

{% endblock %}

MiniBlog/blog/templates/blog/detail_post.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="row">          
        <div class="jumbotron jumbotron-fluid jumbo-color" style="margin-top: 60px;">
              <div class="container">
                <h4 class="display-4  text-center" style="margin-top: -40px;"> {{posts}} </h1><br>
                <p class="lead" style="color:lightseagreen;"> {{posts.desc}} </p>
              </div>
        </div> 
    </div>
{% endblock %}

MiniBlog/blog/templates/blog/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="row">
        <h1 class="text-white my-5"  style="margin:auto;"> Home Page </h3>
        {% for post in posts  %}
          
        <div class="jumbotron jumbotron-fluid jumbo-color">
              <div class="container">
                <h4 class="display-4  text-center" style="margin-top: -40px; color:orange"> {{post}} </h1><br>
                <p class="lead" style="color:lightseagreen;"> {{post.desc|truncatewords:40}} </p>
                <a href="{% url 'Mini-Blog:detail_post' post.id %}" class="btn btn-primary" style="margin-left:500px;">   Read More</a>
              </div>
        </div>
        {% endfor %} 
    </div>
    <nav aria-label="doctor-pagination" style="margin-left:445px; margin-bottom:60px;">
      <ul class="pagination">
          <!-- Start Of Previous -->
              {% if posts.has_previous %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{posts.previous_page_number}}"> Previous </a>
                  </li>
              {% else %}
                  <li class="page-item disabled">
                      <a class="page-link"> Previous </a>
                  </li>
              {% endif %}
          <!-- End Of Previous -->
  
          <!-- Start Of Loop -->
              {% for page_num in posts.paginator.page_range %}
                  {% if posts_num == page_num %}
                      <li class="page-item active">
                           {{page_num}
                          <span class="sr-only">(current)</span>
                      </li>
                  {% else %}
                      <li class="page-item">
                          <a class="page-link" href="?page={{page_num}}"> {{page_num}} </a>
                      </li>
                  {% endif %}
              {% endfor %}
           <!-- Start Of Loop -->
  
  
           <!-- Start Of Next -->
              {% if posts.has_next %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{posts.next_page_number}}"> Next </a>
                  </li>
              {% else %}
                  <li class="page-item disabled">
                      <a class="page-link"> Next </a>
                  </li>
              {% endif %}
          <!-- End Of Next -->
{% endblock %}

MiniBlog/blog/templates/blog/update_post.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="col-sm-10">
        <h1 class="text-white my-5" style="margin:auto; "> Dashboard / Update Post </h3>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Update Post" class="btn btn-success">
            <a href="{% url 'Mini-Blog:dashboard' %}" class="btn btn-danger"> Cancel </a>
        </form>    
    </div>
{% endblock %}

MiniBlog/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Mini-Blog </title>
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
</head>
<body>
<div class="container-fluid bg-dark">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
  <a class="navbar-brand" href="{% url 'Mini-Blog:home' %}" style="margin-top: 6px;"> Mini-Blog </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Mini-Blog:home' %}" style="margin-top:8px;"> Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" style="margin-top: 8px;" href="{% url 'Mini-Blog:contact' %}"> Contact </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" style="margin-top: 8px;;" href="{% url 'Mini-Blog:dashboard' %}"> Dashboard </a>
      </li>

      <div class="col-xl-3 col-lg-3 d-none d-lg-block">
        <div class="Appointment">
          {% if user.is_authenticated%}
             <div class="phone_num d-none d-xl-block">
                <a  class="btn btn-primary" style="margin-left: 820px; margin-top: 10px;"  href="{% url 'accounts:profile' %}">Profile</a>
            </div>
            
            <div class="phone_num d-none d-xl-block">
                <a  class="btn btn-danger" style="margin-left: 900px; margin-top: -34px; padding: 3px;"   href="{% url 'logout' %}"> Logout</a>
            </div>
          {% else %}
           <li class="nav-item active">
                <a  class="btn btn-success" style="margin-left: 820px; margin-bottom:-20px;" href="{% url 'login' %}">Login</a>
           </li>
            <li class="nav-item active">
              <a  class="btn btn-warning"  style="margin-left: 900px; margin-top: -26px;" href="{% url 'accounts:signup' %}"> SignUp </a>
            </li>
           
          {% endif %}
        </div>
    </div>
    </ul>
  </div>
</nav>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            {% block msg %}
            {% endblock %}
        </div>
    </div>
<div class="row">
    {% block side %}
    {% endblock %}
    {% block content %}
    {% endblock %}
</div>
  <div class="col-sm-8">
            {% block content1 %}
            {% endblock %}
  </div>
</div>

<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
<script src="{% static 'blog/js/jquery.js' %}"></script>
<script src="{% static 'blog/js/popper.js' %}"></script>
</body>
</html>